Home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [

    # / - Home Page
    url(r'^$', views.home_page, name='home_page'),
    url('^work/', views.work, name='work'),
    url('^about/', views.about, name='about'),
    url('^contact/', views.contact, name='contact'),
    url('^404/',views.page_not_found,name='404'),
    url('^voting/',views.voting,name='voting'),
    url('^send_mail/',views.query,name='query')
]

its_my_design/urls.py
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin

from its_my_design import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^imagefit/', include('imagefit.urls')),
    url(r'^', include('Home.urls')),

]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models


def category_icon_path(instance, filename):
    extension = filename.split('.')
    extension = extension[len(extension) - 1]
    test = instance.name
    name = ''.join(e for e in test if e.isalnum())
    # print(name)
    return 'Media/Categories/{0}/{1}.{2}'.format(name, name, extension)


def thumbnail_category_icon_path(instance, filename):
    extension = filename.split('.')
    extension = extension[len(extension) - 1]
    name = instance.name
    name = name.replace(" ", "")
    return 'Media/Categories/{0}/{1}.{2}'.format(name, name, extension)


def project_media_path(instance, filename):
    extension = filename.split('.')
    extension = extension[len(extension) - 1]
    name = instance.name
    name = ''.join(e for e in name if e.isalnum())
    return 'Media/Categories/{0}/{1}/{2}.{3}'.format(''.join(e for e in instance.category.name if e.isalnum()), name,
                                                     name,
                                                     extension.lower())


class Carousel(models.Model):
    name = models.CharField(max_length=50, null=True)


class DayHit(models.Model):
    hits = models.IntegerField(default=0)
    date = models.DateField()


class SiteDetail(models.Model):
    total_hits = models.BigIntegerField(default=0)


class Log(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField()


class Category(models.Model):
    name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    created_date = models.DateField()
    logo = models.ImageField(upload_to=category_icon_path)
    rank = models.PositiveIntegerField(null=True)
    text = models.TextField(null=True)

    def __str__(self):
        return self.name + ' ' + str(self.rank)


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    media = models.FileField(upload_to=project_media_path, default=None, blank=True)
    media_type = models.BooleanField(default=0)
    youtube_url = models.URLField(null=True, blank=True)

    def clean(self):

        if self.youtube_url:
            self.media_type = 1
        else:
            video_extensions = ['mp4', 'mov', 'avi', 'mpg', 'wmv']
            image_extensions = ['jpeg', 'jpg', 'pnndfghjg']
            extension = self.media.name.split('.')
            extension = extension[len(extension) - 1]
            if extension.lower() in video_extensions:
                self.media_type = 1
            elif extension.lower() in image_extensions:
                self.media_type = 0
            else:
                raise ValidationError(u'Unsupported file extension.')

    def __str__(self):
        return self.category.name + '-' + self.name


class ContactInfo(models.Model):
    name = models.CharField(max_length=100)
    number = models.BigIntegerField()
    email = models.EmailField()
    address = models.CharField(max_length=500)

    def __str__(self):
        return self.name + str(self.number) + str(self.email)


class Query(models.Model):
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    description = models.CharField(max_length=500)

Home/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
# Create your views here.
from Home.models import Category, Query
from django.conf import settings

from django.core.mail import send_mail


def home_page(request):
    all_category = Category.objects.filter(is_active=True).order_by('rank')
    return render(request, "home.html", {
        'all_category': all_category,
        'width_percent': 20
    })


def work(request):
    category = request.GET.get('category')
    # all category same as above
    category_obj = get_object_or_404(Category, name=category)
    projects = category_obj.project_set.all()
    if projects.__len__() == 0:
        return render(request, 'election_campaign.html', {
            'category': category_obj
        })
    # projects = sorted(projects,key=lambda x:x.rank)
    # print(category_obj.text)
    return render(request, "work.html", {
        'project_type_name': category_obj,
        'all_category': projects,
    })


def about(request):
    return render(request, "about.html")


def contact(request):
    return render(request, "contact.html")


def page_not_found(request):
    return render(request, '404.html')


def voting(request):
    return render(request, 'voting.html')


def query(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        subject = request.POST.get('subject')
        description = request.POST.get('description')
        obj = Query.objects.create(email=email, first_name=fname, last_name=lname, subject=subject,
                                   description=description)

        message = "<h3>You have query received from " + fname + " " + lname + ".</h3>"
        message += "<h3>And has provided this mail for communication<h3>" + email + "<h2>Description : </h2><0=h2>" + description + "</h2>"
        obj.save()
        send_mail(subject,
                  message,
                  email,
                  ['itsmydesignbrand@gmail.com'], fail_silently=False, html_message=message)
        return redirect('/contact/')

    else:
        return HttpResponse('Something went wrong')

Home/templates/contact.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Its My Design</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content=""/>
    <meta name="keywords"
          content=""/>
    <meta name="author" content=""/>


    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'Home/css/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'Home/css/icomoon.css' %}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'Home/css/bootstrap.css' %}">
    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="{% static 'Home/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'Home/css/owl.theme.default.min.css' %}">
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'Home/css/style.css' %}">
    <!-- Modernizr JS -->
    <script src="{% static 'Home/js/modernizr-2.6.2.min.js' %}"></script>


</head>
<body>
<div class="fh5co-loader"></div>

<div id="page">
    <nav class="fh5co-nav" role="navigation">
        <div class="top">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 text-right">
                        <p class="num"><a href="tel://+91 8485800921">+91 8485800921</a></p>
                        <ul class="fh5co-social">
                            <li><a href="#"><i class="icon-twitter" style="color: #1baae1;"></i></a></li>
                            <li><a href="#"><i class="icon-dribbble" style="color:#ea4c89;"></i></a></li>
                            <li><a href="#"><i class="icon-github" style="color: #211F1F;"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="top-menu">
            <div class="container">
                <div class="row">
                    <div class="col-xs-2">
                        <div id="fh5co-logo">
                            <a href="/">
                                <span>
                                    <img src="{% static 'Home/images/logo.png' %}" width="100">
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-10 text-right menu-1">
                        <ul>
                            <li><a href="{% url 'home:home_page' %}" class="nav-link">Home</a></li>
                            <li><a href="{% url 'home:home_page' %}#fh5co-project" class="nav-link">Work</a></li>
                            <li><a href="{% url 'home:about' %}" class="nav-link">About us</a></li>
                            <li><a href="{% url 'home:contact' %}" class="nav-link">Contact</a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </nav>

    <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner"
            style="background-image:url('{% static 'Home/images/contact.jpg' %}');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <div class="display-t">
                        <div class="display-tc animate-box" data-animate-effect="fadeIn">
                            <h1>Contact Us</h1>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div id="fh5co-contact">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-md-push-1 animate-box">

                    <div class="fh5co-contact-info">
                        <h3>Contact Information</h3>
                        <ul>
                            <li class="address">39, 1st Floor Kenchi Building,<br>Mahatma Phule Peth, Kasturi Chowk,<br>
                                Ganj Peth, Pune-42
                            </li>
                            <li class="phone"><a href="tel://+91 8788008324">+91 8788008324</a></li>
                            <li class="phone"><a href="tel://91 8485800921">+91 8485800921</a></li>
                            <li class="email"><a href="mailto:itsmydesign.in@gmail.com">itsmydesignbrand@gmail.com</a>
                            </li>
                        </ul>
                    </div>

                </div>
                <form method="post" action="{% url 'home:query' %}">
                    {% csrf_token %}
                    <div class="col-md-6 animate-box">
                        <h3>Get In Touch</h3>
                        <form action="#">
                            <div class="row form-group">
                                <div class="col-md-6">
                                    <!-- <label for="fname">First Name</label> -->
                                    <input type="text" id="fname" name="fname" class="form-control"
                                           placeholder="Your firstname">
                                </div>
                                <div class="col-md-6">
                                    <!-- <label for="lname">Last Name</label> -->
                                    <input type="text" id="lname" name="lname" class="form-control"
                                           placeholder="Your lastname">
                                </div>
                            </div>


                            <div class="row form-group">
                                <div class="col-md-12">
                                    <!-- <label for="email">Email</label> -->
                                    <input required type="email" id="email" name="email" class="form-control"
                                           placeholder="Your email address">
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col-md-12">
                                    <!-- <label for="subject">Subject</label> -->
                                    <input list="categories" type="text" id="subject" name="subject"
                                           class="form-control"
                                           placeholder="Your subject of this message">

                                    <datalist id="categories">
                                        <option value="Logo Design">
                                        <option value="Election Campaign">
                                        <option value="3d Graphics and Animation">
                                        <option value="Web Design">
                                        <option value="Combo Pack (Website, Logo, Animation)">
                                    </datalist>
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col-md-12">
                                    <!-- <label for="message">Message</label> -->
                                    <textarea name="description" id="message" cols="30" rows="10" class="form-control"
                                              placeholder="Decription that will help us to guide you in the right direction."></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Send Message" class="btn btn-primary">
                            </div>

                        </form>
                    </div>
                </form>
            </div>

        </div>
    </div>

    <footer id="fh5co-footer" role="contentinfo">
        <div class="container">
            <div class="row row-pb-md">
                <div class="col-md-4 fh5co-widget">
                    <h3>A Little About Its My Design.</h3>
                    <p>Its My Design is one of the leading company in design industry.Providing high quality solution
                        for your brand. </p>
                    <p><a class="btn btn-primary btn-outline with-arrow" href="{% url 'home:about' %}">Learn More <i
                            class="icon-arrow-right"></i></a></p>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                    <ul class="fh5co-footer-links">
                        <li><a href="#">About</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">Terms</a></li>
                        <li><a href="#">Meetups</a></li>
                    </ul>
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                    <ul class="fh5co-footer-links">
                        <li><a href="#">Shop</a></li>
                        <li><a href="#">Privacy</a></li>
                        <li><a href="#">Testimonials</a></li>
                        <li><a href="#">Handbook</a></li>
                        <li><a href="#">Held Desk</a></li>
                    </ul>
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                    <ul class="fh5co-footer-links">
                        <li><a href="#">Find Designers</a></li>
                        <li><a href="#">Find Developers</a></li>
                        <li><a href="#">Teams</a></li>
                        <li><a href="#">Advertise</a></li>
                        <li><a href="#">API</a></li>
                    </ul>
                </div>
            </div>

            <div class="row copyright">
                <div class="col-md-12 text-center">
                    <p>
                        <small class="block">&copy; 2018 Its My Design. All Rights Reserved.</small>
                        <small class="block">Designed by <a href="#" target="_blank">Its My Design</a>
                        </small>
                    </p>
                    <p>
                    <ul class="fh5co-social-icons">
                        <li><a href="#"><i class="icon-twitter" style="color: #1baae1;"></i></a></li>
                        <li><a href="#"><i class="icon-facebook" style="color: #3b5998;"></i></a></li>
                        <li><a href="#"><i class="icon-linkedin" style="color: #4875b4;"></i></a></li>
                        <li><a href="#"><i class="icon-dribbble" style="color:#ea4c89; "></i></a></li>
                    </ul>
                    </p>
                </div>
            </div>

        </div>
    </footer>
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>


<!-- jQuery -->
<script src="{% static 'Home/js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'Home/js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'Home/js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'Home/js/jquery.waypoints.min.js' %}"></script>
<!-- Stellar Parallax -->
<script src="{% static 'Home/js/jquery.stellar.min.js' %}"></script>
<!-- Carousel -->
<script src="{% static 'Home/js/owl.carousel.min.js' %}"></script>
<!-- Main -->
<script src="{% static 'Home/js/main.js' %}"></script>
</body>
</html>

Home/templates/election_campaign.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Its My Design</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content=""/>
    <meta name="keywords"
          content=""/>
    <meta name="author" content=""/>


    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'Home/css/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'Home/css/icomoon.css' %}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'Home/css/bootstrap.css' %}">
    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="{% static 'Home/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'Home/css/owl.theme.default.min.css' %}">
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'Home/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Vesper+Libre" rel="stylesheet">

    <!-- Modernizr JS -->
    <script src="{% static 'Home/js/modernizr-2.6.2.min.js' %}"></script>
    <style>
        .marathi-text {
            font-family: 'Vesper Libre', cursive;
            font-size: 1.5em;
        }
    </style>

</head>
<body>
<div class="fh5co-loader"></div>

<div id="page">
    <nav class="fh5co-nav" role="navigation">
        <div class="top">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 text-right">
                        <p class="num"><a href="tel://+91 8485800921">+91 8485800921</a></p>
                        <ul class="fh5co-social">
                            <li><a href="#"><i class="icon-twitter" style="color: #1baae1;"></i></a></li>
                            <li><a href="#"><i class="icon-dribbble" style="color:#ea4c89;"></i></a></li>
                            <li><a href="#"><i class="icon-github" style="color: #211F1F;"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="top-menu">
            <div class="container">
                <div class="row">
                    <div class="col-xs-2">
                        <div id="fh5co-logo">
                            <a href="/">
                                <span>
                                    <img src="{% static 'Home/images/logo.png' %}" width="100">
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="col-xs-10 text-right menu-1">
                        <ul>
                            <li><a href="{% url 'home:home_page' %}" class="nav-link">Home</a></li>
                            <li><a href="{% url 'home:home_page' %}#fh5co-project" class="nav-link">Work</a></li>
                            <li><a href="{% url 'home:about' %}" class="nav-link">About us</a></li>
                            <li><a href="{% url 'home:contact' %}" class="nav-link">Contact</a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </nav>

    <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner"
            style="background-image:url('{% static 'Home/images/contact.jpg' %}');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <div class="display-t">
                        <div class="display-tc animate-box" data-animate-effect="fadeIn">
                            <h1>Contact Us</h1>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div id="fh5co-contact">
        <div class="container">
            <div class="row text-center">
                <h1 class="marathi-text">निवडणूक प्रचार</h1>
                <div class="col-md-2"></div>
                <div class="col-md-8 marathi-text">
                    {{ category.text|linebreaks }}
                </div>
                <div class="col-md-2"></div>

            </div>
            <br>
            <br>
            <div class="row">
                <div class="col-md-5 col-md-push-1 animate-box">

                    <div class="fh5co-contact-info">
                        <h3>Contact Information</h3>
                        <ul>
                            <li class="address">39, 1st Floor Kenchi Building,<br>Mahatma Phule Peth, Kasturi Chowk,<br>
                                Ganj Peth, Pune-42
                            </li>
                            <li class="phone"><a href="tel://+91 8788008324">+91 8788008324</a></li>
                            <li class="phone"><a href="tel://91 8485800921">+91 8485800921</a></li>
                            <li class="email"><a href="mailto:itsmydesign.in@gmail.com">itsmydesignbrand@gmail.com</a>
                            </li>
                        </ul>
                    </div>

                </div>
                <form method="post" action="{% url 'home:query' %}">
                    {% csrf_token %}
                    <div class="col-md-6 animate-box">
                        <h3>Get In Touch</h3>
                        <form action="#">
                            <div class="row form-group">
                                <div class="col-md-6">
                                    <!-- <label for="fname">First Name</label> -->
                                    <input type="text" id="fname" name="fname" class="form-control"
                                           placeholder="Your firstname">
                                </div>
                                <div class="col-md-6">
                                    <!-- <label for="lname">Last Name</label> -->
                                    <input type="text" id="lname" name="lname" class="form-control"
                                           placeholder="Your lastname">
                                </div>
                            </div>


                            <div class="row form-group">
                                <div class="col-md-12">
                                    <!-- <label for="email">Email</label> -->
                                    <input required type="email" id="email" name="email" class="form-control"
                                           placeholder="Your email address">
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col-md-12">
                                    <!-- <label for="subject">Subject</label> -->
                                    <input list="categories" type="text" id="subject" name="subject"
                                           class="form-control"
                                           placeholder="Your subject of this message">

                                    <datalist id="categories">
                                        <option value="Logo Design">
                                        <option value="Election Campaign">
                                        <option value="3d Graphics and Animation">
                                        <option value="Web Design">
                                        <option value="Combo Pack (Website, Logo, Animation)">
                                    </datalist>
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col-md-12">
                                    <!-- <label for="message">Message</label> -->
                                    <textarea name="description" id="message" cols="30" rows="10" class="form-control"
                                              placeholder="Decription that will help us to guide you in the right direction."></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Send Message" class="btn btn-primary">
                            </div>

                        </form>
                    </div>
                </form>
            </div>

        </div>
    </div>

    <footer id="fh5co-footer" role="contentinfo">
        <div class="container">
            <div class="row row-pb-md">
                <div class="col-md-4 fh5co-widget">
                    <h3>A Little About Its My Design.</h3>
                    <p>Its My Design is one of the leading company in design industry.Providing high quality solution
                        for your brand. </p>
                    <p><a class="btn btn-primary btn-outline with-arrow" href="{% url 'home:about' %}">Learn More <i
                            class="icon-arrow-right"></i></a></p>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                    <ul class="fh5co-footer-links">
                        <li><a href="#">About</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">Terms</a></li>
                        <li><a href="#">Meetups</a></li>
                    </ul>
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                    <ul class="fh5co-footer-links">
                        <li><a href="#">Shop</a></li>
                        <li><a href="#">Privacy</a></li>
                        <li><a href="#">Testimonials</a></li>
                        <li><a href="#">Handbook</a></li>
                        <li><a href="#">Held Desk</a></li>
                    </ul>
                </div>

                <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                    <ul class="fh5co-footer-links">
                        <li><a href="#">Find Designers</a></li>
                        <li><a href="#">Find Developers</a></li>
                        <li><a href="#">Teams</a></li>
                        <li><a href="#">Advertise</a></li>
                        <li><a href="#">API</a></li>
                    </ul>
                </div>
            </div>

            <div class="row copyright">
                <div class="col-md-12 text-center">
                    <p>
                        <small class="block">&copy; 2018 Its My Design. All Rights Reserved.</small>
                        <small class="block">Designed by <a href="#" target="_blank">Its My Design</a>
                        </small>
                    </p>
                    <p>
                    <ul class="fh5co-social-icons">
                        <li><a href="#"><i class="icon-twitter" style="color: #1baae1;"></i></a></li>
                        <li><a href="#"><i class="icon-facebook" style="color: #3b5998;"></i></a></li>
                        <li><a href="#"><i class="icon-linkedin" style="color: #4875b4;"></i></a></li>
                        <li><a href="#"><i class="icon-dribbble" style="color:#ea4c89; "></i></a></li>
                    </ul>
                    </p>
                </div>
            </div>

        </div>
    </footer>
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>


<!-- jQuery -->
<script src="{% static 'Home/js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'Home/js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'Home/js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'Home/js/jquery.waypoints.min.js' %}"></script>
<!-- Stellar Parallax -->
<script src="{% static 'Home/js/jquery.stellar.min.js' %}"></script>
<!-- Carousel -->
<script src="{% static 'Home/js/owl.carousel.min.js' %}"></script>
<!-- Main -->
<script src="{% static 'Home/js/main.js' %}"></script>
</body>
</html>